## Data Cleaning  
In this notebook the mpesa statement analysis csv file is cleaned to extract important information and remove unnecessary columns and unnecessary information using python pandas workframe

In [1]:
import pandas as pd
df = pd.read_csv("C:/Users/alfie/OneDrive/Documentos/PROJECT_FOLDER/statements.csv")
df.head()

,Receipt No,Completion Date Time,Details,Transaction Status,Paid in,Withdraw n,Balance,Date,Time2,Date3
0,TKTLABHGPA,29/11/2025 21:41,M-Shwari Withdraw,COMPLETED,100,0,130,NaN,NaN,NaN
1,TKTLABH0S2,29/11/2025 20:55,Customer Payment to Small Business to 0704***1...,COMPLETED,0,40,30,NaN,NaN,NaN
2,TKTLABH3MF,29/11/2025 20:49,Customer Payment to Small Business to 254715**...,COMPLETED,0,20,70,NaN,NaN,NaN
3,TKTLABH1V3,29/11/2025 20:39,Merchant Payment to 5042130 - OSCAR MWATHU,COMPLETED,0,100,90,NaN,NaN,NaN
4,TKTLABH0FX,29/11/2025 20:38,M-Shwari Withdraw,COMPLETED,100,0,190,NaN,NaN,NaN

In [2]:
df = df.drop(columns=["Date", "Time2", "Date3", "Transaction Status"])
df.head()

,Receipt No,Completion Date Time,Details,Paid in,Withdraw n,Balance
0,TKTLABHGPA,29/11/2025 21:41,M-Shwari Withdraw,100,0,130
1,TKTLABH0S2,29/11/2025 20:55,Customer Payment to Small Business to 0704***1...,0,40,30
2,TKTLABH3MF,29/11/2025 20:49,Customer Payment to Small Business to 254715**...,0,20,70
3,TKTLABH1V3,29/11/2025 20:39,Merchant Payment to 5042130 - OSCAR MWATHU,0,100,90
4,TKTLABH0FX,29/11/2025 20:38,M-Shwari Withdraw,100,0,190

In [3]:
# check the data tyoes of each column
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 259 entries, 0 to 258
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Receipt No            259 non-null    str
 1   Completion Date Time  259 non-null    str
 2   Details               259 non-null    str
 3   Paid in               259 non-null    int64
 4   Withdraw n            259 non-null    int64
 5   Balance               259 non-null    int64
dtypes: int64(3), str(3)
memory usage: 33.5 KB

### Extract meaningful info from the details column
In the code below python regex functions was applied to simplify the details column to only include crucial information about the type of transaction without including the details of where the money was recieved from or sent to.  
This was achieved using a regex function that extracts all the characters from the beginning of the statement until we encounter the first digits.

In [4]:
import re
pattern = r"^(\D*)"
df["Details"] = df["Details"].str.extract(pattern)
df["Details"] = df["Details"].str.strip()
df.head()

,Receipt No,Completion Date Time,Details,Paid in,Withdraw n,Balance
0,TKTLABHGPA,29/11/2025 21:41,M-Shwari Withdraw,100,0,130
1,TKTLABH0S2,29/11/2025 20:55,Customer Payment to Small Business to,0,40,30
2,TKTLABH3MF,29/11/2025 20:49,Customer Payment to Small Business to,0,20,70
3,TKTLABH1V3,29/11/2025 20:39,Merchant Payment to,0,100,90
4,TKTLABH0FX,29/11/2025 20:38,M-Shwari Withdraw,100,0,190

In [5]:
df["Details"].unique()

<ArrowStringArray>
[                    'M-Shwari Withdraw',
 'Customer Payment to Small Business to',
                   'Merchant Payment to',
           'Customer Bundle Purchase to',
                              'Offnet C',
                           'Pay Bill to',
                   'Funds received from',
                  'Customer Transfer to',
                    'Transfer from Bank',
                       'Pay Bill Charge',
                      'Airtime Purchase',
     'Customer Transfer of Funds Charge',
                      'M-Shwari Deposit',
            'Merchant Payment Online to']
Length: 14, dtype: str

After the above process the number of unique rows as per the details column reduced to 14. The next step is to make these details more simplified but still retain the meaning.

In [6]:
df[df["Details"]=="Customer Transfer of Funds Charge"]

,Receipt No,Completion Date Time,Details,Paid in,Withdraw n,Balance
101,TKNLAAVRG9,23/11/2025 10:04,Customer Transfer of Funds Charge,0,7,141
126,TKLLAAR81Z,21/11/2025 19:15,Customer Transfer of Funds Charge,0,7,573
147,TKKLAAO1ET,20/11/2025 20:02,Customer Transfer of Funds Charge,0,7,236
214,TKGLAAAZLH,16/11/2025 15:24,Customer Transfer of Funds Charge,0,7,19
238,TKELAA6327,14/11/2025 20:38,Customer Transfer of Funds Charge,0,53,346

In [7]:
def standardize_details(df, column="Details"):
    """
    Standardize transaction description in the specified column
    """
    replacements = {
        "Customer Payment to Small Business to":"Payment small business",
        "Merchant Payment to":"Merchant payment",
        "Customer Bundle Purchase to":"Bundle purchase",
        "Offnet C":"Offnet Transfer",
        "Pay Bill to":"Paybill",
        "Funds received from":"Funds recieved",
        "Customer Transfer to":"Send money",
        "Transfer from Bank":"Bank transfer",
        "Customer Transfer of Funds Charge":"Send money charges",
        "Merchant Payment Online to":"Merchant payment"
    }
    df[column] = df[column].replace(replacements)
    return df

df = standardize_details(df,column="Details")

In [8]:
df.head()

,Receipt No,Completion Date Time,Details,Paid in,Withdraw n,Balance
0,TKTLABHGPA,29/11/2025 21:41,M-Shwari Withdraw,100,0,130
1,TKTLABH0S2,29/11/2025 20:55,Payment small business,0,40,30
2,TKTLABH3MF,29/11/2025 20:49,Payment small business,0,20,70
3,TKTLABH1V3,29/11/2025 20:39,Merchant payment,0,100,90
4,TKTLABH0FX,29/11/2025 20:38,M-Shwari Withdraw,100,0,190

In [9]:
df = df.drop(columns=["Balance"])

In [10]:
# sort by the completion date column
df = df.sort_values(by="Completion Date Time", ascending=True)
df

,Receipt No,Completion Date Time,Details,Paid in,Withdraw n
244,TKELAA535O,14/11/2025 18:10,Payment small business,0,30
242,TKELAA5EMK,14/11/2025 18:39,Payment small business,0,10
243,TKELAA5G4Q,14/11/2025 18:39,Payment small business,0,100
241,TKELAA5GXE,14/11/2025 19:07,Bundle purchase,0,10
240,TKELAA630Y,14/11/2025 20:36,M-Shwari Withdraw,3500,0
...,...,...,...,...,...
249,TKUI8BM7ZD,30/11/2025 17:00,Funds recieved,500,0
248,TKULABJN7L,30/11/2025 17:15,Send money,0,10
247,TKULABKFU9,30/11/2025 21:35,Payment small business,0,26
246,TKULABKBGG,30/11/2025 21:38,Payment small business,0,20
245,TKULABKJ1H,30/11/2025 21:45,Payment small business,0,25

In [11]:
# conevert the date time column to datetime 
df["Completion Date Time"] = pd.to_datetime(df["Completion Date Time"], dayfirst = True)

# create a new column to categorise the time as morning, afternoon, evening, night
df["Hour"] = df["Completion Date Time"].dt.hour
# categorise
# pd.cut is a method used to categorise or sort values into bins
df["Period"] = pd.cut(x=df["Hour"],
                     bins=[0,12,16,20,24],
                     labels = ["morning", "afternoon", "evening", "night"])

In [12]:
df

,Receipt No,Completion Date Time,Details,Paid in,Withdraw n,Hour,Period
244,TKELAA535O,2025-11-14 18:10:00,Payment small business,0,30,18,evening
242,TKELAA5EMK,2025-11-14 18:39:00,Payment small business,0,10,18,evening
243,TKELAA5G4Q,2025-11-14 18:39:00,Payment small business,0,100,18,evening
241,TKELAA5GXE,2025-11-14 19:07:00,Bundle purchase,0,10,19,evening
240,TKELAA630Y,2025-11-14 20:36:00,M-Shwari Withdraw,3500,0,20,evening
...,...,...,...,...,...,...,...
249,TKUI8BM7ZD,2025-11-30 17:00:00,Funds recieved,500,0,17,evening
248,TKULABJN7L,2025-11-30 17:15:00,Send money,0,10,17,evening
247,TKULABKFU9,2025-11-30 21:35:00,Payment small business,0,26,21,night
246,TKULABKBGG,2025-11-30 21:38:00,Payment small business,0,20,21,night
245,TKULABKJ1H,2025-11-30 21:45:00,Payment small business,0,25,21,night

In [13]:
df["Completion Date Time"] = pd.to_datetime(df["Completion Date Time"], dayfirst=True)
df.info()

<class 'pandas.DataFrame'>
Index: 259 entries, 244 to 245
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Receipt No            259 non-null    str
 1   Completion Date Time  259 non-null    datetime64[us]
 2   Details               259 non-null    str
 3   Paid in               259 non-null    int64
 4   Withdraw n            259 non-null    int64
 5   Hour                  259 non-null    int32
 6   Period                259 non-null    category
dtypes: category(1), datetime64[us](1), int32(1), int64(2), str(2)
memory usage: 20.8 KB

In [14]:
df

,Receipt No,Completion Date Time,Details,Paid in,Withdraw n,Hour,Period
244,TKELAA535O,2025-11-14 18:10:00,Payment small business,0,30,18,evening
242,TKELAA5EMK,2025-11-14 18:39:00,Payment small business,0,10,18,evening
243,TKELAA5G4Q,2025-11-14 18:39:00,Payment small business,0,100,18,evening
241,TKELAA5GXE,2025-11-14 19:07:00,Bundle purchase,0,10,19,evening
240,TKELAA630Y,2025-11-14 20:36:00,M-Shwari Withdraw,3500,0,20,evening
...,...,...,...,...,...,...,...
249,TKUI8BM7ZD,2025-11-30 17:00:00,Funds recieved,500,0,17,evening
248,TKULABJN7L,2025-11-30 17:15:00,Send money,0,10,17,evening
247,TKULABKFU9,2025-11-30 21:35:00,Payment small business,0,26,21,night
246,TKULABKBGG,2025-11-30 21:38:00,Payment small business,0,20,21,night
245,TKULABKJ1H,2025-11-30 21:45:00,Payment small business,0,25,21,night

In [15]:
print(len(df))

259

In [16]:
len(df['Receipt No'].unique())

250

In [17]:
df[df['Receipt No'].duplicated()]

,Receipt No,Completion Date Time,Details,Paid in,Withdraw n,Hour,Period
239,TKELAA6327,2025-11-14 20:38:00,Payment small business,0,3200,20,evening
215,TKGLAAAZLH,2025-11-16 15:24:00,Payment small business,0,150,15,afternoon
183,TKILAAHAFA,2025-11-18 17:01:00,Paybill,0,4500,17,evening
180,TKILAAHG9U,2025-11-18 17:49:00,Paybill,0,800,17,evening
148,TKKLAAO1ET,2025-11-20 20:02:00,Payment small business,0,175,20,evening
127,TKLLAAR81Z,2025-11-21 19:15:00,Payment small business,0,120,19,evening
102,TKNLAAVRG9,2025-11-23 10:04:00,Send money,0,500,10,morning
70,TKPLAB1JAI,2025-11-25 09:02:00,Paybill,0,155,9,morning
254,TKULABI43N,2025-11-30 09:02:00,Pay Bill Charge,0,5,9,morning

In [18]:
df[df["Details"].str.lower() == "pay bill charge"]

,Receipt No,Completion Date Time,Details,Paid in,Withdraw n,Hour,Period
182,TKILAAHAFA,2025-11-18 17:01:00,Pay Bill Charge,0,34,17,evening
179,TKILAAHG9U,2025-11-18 17:49:00,Pay Bill Charge,0,10,17,evening
69,TKPLAB1JAI,2025-11-25 09:02:00,Pay Bill Charge,0,5,9,morning
254,TKULABI43N,2025-11-30 09:02:00,Pay Bill Charge,0,5,9,morning

In [19]:
print(df.isnull().sum())

Receipt No              0
Completion Date Time    0
Details                 0
Paid in                 0
Withdraw n              0
Hour                    0
Period                  0
dtype: int64

### creating a database engine connection

In [20]:
# rename columns to match database columns
df.rename(columns={
    "Receipt No":"receipt_no",
    "Completion Date Time":"completion_date",
    "Details":"transaction_details",
    "Paid in":"paid_in",
    "Withdraw n":"withdrawn",
    "Hour":"hour",
    "Period":"period"
}, inplace=True)

In [21]:
df

,receipt_no,completion_date,transaction_details,paid_in,withdrawn,hour,period
244,TKELAA535O,2025-11-14 18:10:00,Payment small business,0,30,18,evening
242,TKELAA5EMK,2025-11-14 18:39:00,Payment small business,0,10,18,evening
243,TKELAA5G4Q,2025-11-14 18:39:00,Payment small business,0,100,18,evening
241,TKELAA5GXE,2025-11-14 19:07:00,Bundle purchase,0,10,19,evening
240,TKELAA630Y,2025-11-14 20:36:00,M-Shwari Withdraw,3500,0,20,evening
...,...,...,...,...,...,...,...
249,TKUI8BM7ZD,2025-11-30 17:00:00,Funds recieved,500,0,17,evening
248,TKULABJN7L,2025-11-30 17:15:00,Send money,0,10,17,evening
247,TKULABKFU9,2025-11-30 21:35:00,Payment small business,0,26,21,night
246,TKULABKBGG,2025-11-30 21:38:00,Payment small business,0,20,21,night
245,TKULABKJ1H,2025-11-30 21:45:00,Payment small business,0,25,21,night

### further improvement
the paid_in and withdrawn columns led to cluttering and i was unable to use legend when building dashboard. Furthermore i needed to use filters every time when creating visusals. This led to the idea of combining the columns and creating an extra column that indicates if the transaction is an expense or an income

In [22]:
# create a new column that specifies if the transacton is expense or income
df["direction"] = df["withdrawn"].apply(lambda x:"expense" if x>0 else "income")
# combine the paid in and withdrawn into one column named amount
df["amount"] = df["paid_in"]+df["withdrawn"]

# drop the paid in and withdrawn columns
df.drop(columns=["paid_in", "withdrawn"], inplace=True)

df

,receipt_no,completion_date,transaction_details,hour,period,direction,amount
244,TKELAA535O,2025-11-14 18:10:00,Payment small business,18,evening,expense,30
242,TKELAA5EMK,2025-11-14 18:39:00,Payment small business,18,evening,expense,10
243,TKELAA5G4Q,2025-11-14 18:39:00,Payment small business,18,evening,expense,100
241,TKELAA5GXE,2025-11-14 19:07:00,Bundle purchase,19,evening,expense,10
240,TKELAA630Y,2025-11-14 20:36:00,M-Shwari Withdraw,20,evening,income,3500
...,...,...,...,...,...,...,...
249,TKUI8BM7ZD,2025-11-30 17:00:00,Funds recieved,17,evening,income,500
248,TKULABJN7L,2025-11-30 17:15:00,Send money,17,evening,expense,10
247,TKULABKFU9,2025-11-30 21:35:00,Payment small business,21,night,expense,26
246,TKULABKBGG,2025-11-30 21:38:00,Payment small business,21,night,expense,20
245,TKULABKJ1H,2025-11-30 21:45:00,Payment small business,21,night,expense,25

### Creating an engine to connect to mysql workbench and insert the data to my already created database schema and table

In [23]:
# !pip install pymysql

In [25]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:14222Alfie@localhost/mpesa_statements_db")

df.to_sql("statements",engine, if_exists='append', index=False)

259

### Export the cleaned data to a csv
Export the csv data to csv for use in Exploratory data analysis in mysql workbench and also easier upload in microsoft power bi

In [26]:
df.to_csv("C:/Users/alfie/OneDrive/Documentos/PROJECT_FOLDER/statements_cleaned.csv", index=False)